In [36]:
import numpy as np
import pandas as pd

Imported two libraries, Numpy and Pandas as np and pd.

In [43]:
df = pd.read_csv('../data/raw/NFHS-main/NFHS-main/India.csv')

C:\Users\HELLABA\AppData\Local\Temp\ipykernel_21388\2136339274.py:1: DtypeWarning: Columns (0: DT_CEN_CD) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/NFHS-main/NFHS-main/India.csv')

pd.read_csv is a method that reads the csv data set. Use pd.read_excel if the files are in .xlsx or .xls

In [44]:
df.shape

(73632, 9)

.shape returns the number of rows and columns in the data set

In [45]:
df.head()

,State,ST_CEN_CD,District,DISTRICT,DT_CEN_CD,Category,Indicator,NFHS 5,NFHS 4
0,Andaman & Nicobar Island,35,Nicobar,Nicobar_1,1.0,Population and Household Profile,Female population age 6 years and above who ev...,78.0,77.2
1,Andaman & Nicobar Island,35,Nicobar,Nicobar_1,1.0,Population and Household Profile,Population below age 15 years (%),23.0,25.4
2,Andaman & Nicobar Island,35,Nicobar,Nicobar_1,1.0,Population and Household Profile,Sex ratio of the total population (females per...,973.0,957.0
3,Andaman & Nicobar Island,35,Nicobar,Nicobar_1,1.0,Population and Household Profile,Sex ratio at birth for children born in the la...,927.0,1060.0
4,Andaman & Nicobar Island,35,Nicobar,Nicobar_1,1.0,Population and Household Profile,Children under age 5 years whose birth was reg...,98.0,99.3

.head() method returns the first few rows of the set; if no value is specified, it returns 5 rows

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73632 entries, 0 to 73631
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      73632 non-null  str
 1   ST_CEN_CD  73632 non-null  int64
 2   District   73632 non-null  str
 3   DISTRICT   66976 non-null  str
 4   DT_CEN_CD  66872 non-null  object
 5   Category   73632 non-null  str
 6   Indicator  73632 non-null  str
 7   NFHS 5     73632 non-null  float64
 8   NFHS 4     73632 non-null  float64
dtypes: float64(2), int64(1), object(1), str(5)
memory usage: 5.1+ MB

.info() returns the columns, non-null values and data type. Some values of DISTRICT and DT_CEN_CD are null, need to inspect this properly

In [47]:
df.describe()

          ST_CEN_CD        NFHS 5        NFHS 4
count  73632.000000  73632.000000  73632.000000
mean      17.761299     89.456063     62.071806
std        9.829305    439.057470    391.959863
min        1.000000      0.000000      0.000000
25%        9.000000      5.800000      0.000000
50%       18.500000     28.200000      3.500000
75%       24.000000     73.400000     49.100000
max       36.000000  20101.000000  31457.000000

In [48]:
df['Category'].unique()

<StringArray>
[                          'Population and Household Profile',
                                   'Characteristics of Women',
                                     'Marriage and Fertility',
                     'Current Use of Family Planning Methods',
                             'Unmet Need for Family Planning',
                        'Quality of Family Planning Services',
                                  'Maternal and Child Health',
                                              'Delivery Care',
           'Child Vaccinations and Vitamin A Supplementation',
                            'Treatment of Childhood Diseases',
 'Child Feeding Practices and Nutritional Status of Children',
                                'Nutritional Status of Women',
                           'Anaemia among Children and Women',
                              'Blood Sugar Level among women',
                                'Blood Sugar Level among men',
                                   'Hypertension among women',
                                     'Hypertension among men',
                           'Screening for Cancer among Women',
           'Tobacco Use and Alcohol Consumption among Adults']
Length: 19, dtype: str